#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Can_levels; end

class Can_levels
  include ::Thrift::Struct, ::Thrift::Struct_Union
  COUNT = 1
  CAN_LEVELS = 2

  FIELDS = {
    COUNT => {:type => ::Thrift::Types::I32, :name => 'count'},
    CAN_LEVELS => {:type => ::Thrift::Types::MAP, :name => 'can_levels', :key => {:type => ::Thrift::Types::I64}, :value => {:type => ::Thrift::Types::DOUBLE}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

